package io.github.cloudyhug.praefektur

object GameData {
  val frenchCounties: Array<CountyDatum> = arrayOf(
    CountyDatum(1, "Ain", "Bourg-en-Bresse"),
    CountyDatum(2, "Aisne", "Laon"),
    CountyDatum(3, "Allier", "Moulins"),
    CountyDatum(4, "Alpes-de-Haute-Provence", "Digne-les-bains"),
    CountyDatum(5, "Hautes-Alpes", "Gap"),
    CountyDatum(6, "Alpes-Maritimes", "Nice"),
    CountyDatum(7, "Ardèche", "Privas"),
    CountyDatum(8, "Ardennes", "Charleville-Mézières"),
    CountyDatum(9, "Ariège", "Foix"),
    CountyDatum(10, "Aube", "Troyes"),
    CountyDatum(11, "Aude", "Carcassonne"),
    CountyDatum(12, "Aveyron", "Rodez"),
    CountyDatum(13, "Bouches-du-Rhône", "Marseille"),
    CountyDatum(14, "Calvados", "Caen"),
    CountyDatum(15, "Cantal", "Aurillac"),
    CountyDatum(16, "Charente", "Angoulême"),
    CountyDatum(17, "Charente-Maritime", "La Rochelle"),
    CountyDatum(18, "Cher", "Bourges"),
    CountyDatum(19, "Corrèze", "Tulle"),
    CountyDatum(201, "Corse-du-Sud", "Ajaccio"),
    CountyDatum(202, "Haute-Corse", "Bastia"),
    CountyDatum(21, "Côte-d'Or", "Dijon"),
    CountyDatum(22, "Côtes-d'Armor", "Saint-Brieuc"),
    CountyDatum(23, "Creuse", "Guéret"),
    CountyDatum(24, "Dordogne", "Périgueux"),
    CountyDatum(25, "Doubs", "Besançon"),
    CountyDatum(26, "Drôme", "Valence"),
    CountyDatum(27, "Eure", "Évreux"),
    CountyDatum(28, "Eure-et-Loir", "Chartres"),
    CountyDatum(29, "Finistère", "Quimper"),
    CountyDatum(30, "Gard", "Nîmes"),
    CountyDatum(31, "Haute-Garonne", "Toulouse"),
    CountyDatum(32, "Gers", "Auch"),
    CountyDatum(33, "Gironde", "Bordeaux"),
    CountyDatum(34, "Hérault", "Montpellier"),
    CountyDatum(35, "Ille-et-Vilaine", "Rennes"),
    CountyDatum(36, "Indre", "Châteauroux"),
    CountyDatum(37, "Indre-et-Loire", "Tours"),
    CountyDatum(38, "Isère", "Grenoble"),
    CountyDatum(39, "Jura", "Lons-le-Saunier"),
    CountyDatum(40, "Landes", "Mont-de-Marsan"),
    CountyDatum(41, "Loir-et-Cher", "Blois"),
    CountyDatum(42, "Loire", "Saint-Étienne"),
    CountyDatum(43, "Haute-Loire", "Le Puy-en-Velay"),
    CountyDatum(44, "Loire-Atlantique", "Nantes"),
    CountyDatum(45, "Loiret", "Orléans"),
    CountyDatum(46, "Lot", "Cahors"),
    CountyDatum(47, "Lot-et-Garonne", "Agen"),
    CountyDatum(48, "Lozère", "Mende"),
    CountyDatum(49, "Maine-et-Loire", "Angers"),
    CountyDatum(50, "Manche", "Saint-Lô"),
    CountyDatum(51, "Marne", "Châlons-en-Champagne"),
    CountyDatum(52, "Haute-Marne", "Chaumont"),
    CountyDatum(53, "Mayenne", "Laval"),
    CountyDatum(54, "Meurthe-et-Moselle", "Nancy"),
    CountyDatum(55, "Meuse", "Bar-le-Duc"),
    CountyDatum(56, "Morbihan", "Vannes"),
    CountyDatum(57, "Moselle", "Metz"),
    CountyDatum(58, "Nièvre", "Nevers"),
    CountyDatum(59, "Nord", "Lille"),
    CountyDatum(60, "Oise", "Beauvais"),
    CountyDatum(61, "Orne", "Alençon"),
    CountyDatum(62, "Pas-de-Calais", "Arras"),
    CountyDatum(63, "Puy-de-Dôme", "Clermont-Ferrand"),
    CountyDatum(64, "Pyrénées-Atlantiques", "Pau"),
    CountyDatum(65, "Hautes-Pyrénées", "Tarbes"),
    CountyDatum(66, "Pyrénées-Orientales", "Perpignan"),
    CountyDatum(67, "Bas-Rhin", "Strasbourg"),
    CountyDatum(68, "Haut-Rhin", "Colmar"),
    CountyDatum(69, "Rhône", "Lyon"),
    CountyDatum(70, "Haute-Saône", "Vesoul"),
    CountyDatum(71, "Saône-et-Loire", "Mâcon"),
    CountyDatum(72, "Sarthe", "Le Mans"),
    CountyDatum(73, "Savoie", "Chambéry"),
    CountyDatum(74, "Haute-Savoie", "Annecy"),
    CountyDatum(75, "Paris", "Paris"),
    CountyDatum(76, "Seine-Maritime", "Rouen"),
    CountyDatum(77, "Seine-et-Marne", "Melun"),
    CountyDatum(78, "Yvelines", "Versailles"),
    CountyDatum(79, "Deux-Sèvres", "Niort"),
    CountyDatum(80, "Somme", "Amiens"),
    CountyDatum(81, "Tarn", "Albi"),
    CountyDatum(82, "Tarn-et-Garonne", "Montauban"),
    CountyDatum(83, "Var", "Toulon"),
    CountyDatum(84, "Vaucluse", "Avignon"),
    CountyDatum(85, "Vendée", "La Roche-sur-Yon"),
    CountyDatum(86, "Vienne", "Poitiers"),
    CountyDatum(87, "Haute-Vienne", "Limoges"),
    CountyDatum(88, "Vosges", "Épinal"),
    CountyDatum(89, "Yonne", "Auxerre"),
    CountyDatum(90, "Territoire de Belfort", "Belfort"),
    CountyDatum(91, "Essonne", "Évry-Courcouronnes"),
    CountyDatum(92, "Hauts-de-Seine", "Nanterre"),
    CountyDatum(93, "Seine-Saint-Denis", "Bobigny"),
    CountyDatum(94, "Val-de-Marne", "Créteil"),
    CountyDatum(95, "Val-d'Oise", "Cergy"),
    CountyDatum(971, "Guadeloupe", "Basse-Terre"),
    CountyDatum(972, "Martinique", "Fort-de-France"),
    CountyDatum(973, "Guyane", "Cayenne"),
    CountyDatum(974, "La Réunion", "Saint-Denis"),
    CountyDatum(976, "Mayotte", "Mamoudzou")
  )

  fun frenchCountyToString(n: Int): String {
    return when (n) {
      201 -> "2A"
      202 -> "2B"
      else ->
        (if (n < 10) "0" else "") + n.toString()
    }
  }
}